version: "3.8"

services:
    mysqldb:
        image: mysql:8.0
        container_name: "mysql_${APP_NAME}"
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_USER= $MYSQLDB_USER
            - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql
    app:
        container_name: "app_${APP_NAME}"
        depends_on:
            - mysqldb
        build:
            context: ./app
        volumes:
            - ./app:/app
        restart: unless-stopped
        env_file: ./.env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        environment:
            - DB_HOST=mysqldb
            - DB_USER=$MYSQLDB_USER
            - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - DB_NAME=$MYSQLDB_DATABASE
            - DB_PORT=$MYSQLDB_DOCKER_PORT
        stdin_open: true
        tty: true
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1

volumes:
    db:
